### ISSUE TITLE
Session safety w.r.t. connection pools

### ISSUE THREAD

**Issue by msakrejda** [heroku/pg_lock#2]
Does `ActiveRecord::Base.connection.raw_connection` get a connection from a (transaction-oriented) connection pool? Or is this a raw, unpooled database connection? E.g., the Sequel example in the README:

``` ruby
connection = Module do
  def self.exec(sql, bind)
    DB.fetch(sql, bind)
  end
end
```

is problematic, since Sequel does use transaction pooling here, so there's no guarantee that two subsequent statements will run in the same connection, and, perhaps more importantly, that two _separate_ invocations will _not_ run in the same underlying connection.

As a result of that, you could end up running

``` ruby
PgLock.new(name: "all_your_base", connection: my_connection).lock do
  # some long-running task
end
```

in one thread, get backend 1234 (where you run `pg_advisory_lock`), then yield to the user-supplied block (at which point your `pg_advisory_lock` statement to Postgres has returned and you've returned the connection to the Sequel connection pool). If, while the block is running, you run the same code in _another_ thread, that thread could get a connection to the same backend 1234 when _it_ runs `pg_advisory_lock`, be granted the lock (since advisory locks are re-entrant for the same session which obtained the lock in the first place), and yield to the supplied block, and now you have two blocks running concurrently which were ostensibly protected by `PgLock`.

I don't know if the default `ActiveRecord` behavior works, but the Sequel behavior in the README is broken. I don't know how to make it work--maybe something with [Sequel::Database#synchronize](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Database.html#method-i-synchronize)?

**Comment by schneems** [comment]
I think I see what you're saying. I might be missing something but I believe we're safe even with a pooled connection. This lib isn't guaranteed to provide exclusive execution across different threads, only across different processes (as called out in the readme). So if you're counting on on two different invocations of `PGLock#lock` running in the same process to only execute once, you should be using a regular Mutex instead. If that's the case I think it's fine if the same connection gets re-used across multiple threads in the same process, as this lib essentially provides process level locking (though doesn't guarantee it, as different threads may be running in different sessions). Does that seem reasonable? 

I might be missing something, so maybe an example script to force the behavior you're talking about could help.

**Comment by msakrejda** [comment]
> This lib isn't guaranteed to provide exclusive execution across different threads, only across different processes (as called out in the readme).

Is it? I don't see that there--in fact the first line of the README says:

> Uses Postgres advisory locks to enable you to syncronize actions across multiple **threads**, processes, and even machines.

(emphasis added). Did I miss something?

If you do forgo thread-level locking and document that, it should be safe, but the behavior may be surprising from a usability perspective (though I don't have a great answer there, so maybe there's not much else to be done).

**Comment by schneems** [comment]
Sorry, i've been doing work on another branch. The readme isn't updated and forgot I had not merged. Here's the most recent PR https://github.com/heroku/pg_lock/pull/1 the README is updated and the HUGE caveat is called out (fairly clearly I think). Can you take a look and let me know what you think?

**Comment by msakrejda** [comment]
> Sorry, i've been doing work on another branch.

No problem--I imagine you're a little distracted right now =)

And that does make it clearer, but I realized there's another, related potential problem regarding connection pools (see linked comment).
