### ISSUE TITLE
Not working properly on Rails 5

### ISSUE THREAD

**Issue by tbuehlmann** [heroku/pg_lock#4]
Hey there,

first of all: Thanks for writing this library!

When using Rails 5, PgLock doesn't work properly anymore. I'm not sure if it's Rails 5/ActiveRecord/Arel or the pg driver, but the following code from `PgLock::Locket` behaves differently now:

[Source](https://github.com/heroku/pg_lock/blob/28c382709689e40427011aea4c7f8d6d63da914b/lib/pg_lock/locket.rb#L21)

``` ruby
def aquired?
  @lock[0]["pg_try_advisory_lock"] == "t"
rescue
  false
end
```

[Source]()

``` ruby
def active?
  connection.exec(<<-eos, args).getvalue(0,0) == "t"
    SELECT granted
    FROM pg_locks
    WHERE locktype = 'advisory' AND
     pid = pg_backend_pid() AND
     mode = 'ExclusiveLock' AND
     classid = $1 AND
     objid = $2
  eos
end
```

The returned values don't match `"t"`, they are `true` now. A quick fix is available in my [fork](https://github.com/tbuehlmann/pg_lock/commit/0de628cf7486cef1f11eaf40f0c74d0297a9f0ee).

**Comment by schneems** [comment]
Hey, I wrote this for a small gem that I don't actively use much anymore. There's a bunch of other pg lock gems out there if you want to switch to someone elses.

I'm happy to merge a patch though, do you want to send me a PR?

**Comment by tbuehlmann** [comment]
PR arrived. I didn't touch any test, but it greened out for me after being red first. If you prefer distingueshed tests for different versions of Rails/AR/PG, that could take a while.

**Comment by schneems** [comment]
PR was merged, that closed this issue.
